# This file was generated by extconf.rb
module CommandT
  module Metadata
    EXPECTED_RUBY_VERSION = "2.5.0"
    EXPECTED_RUBY_PATCHLEVEL = 0
    UNKNOWN = false
  end # module Metadata
end # module CommandT
