# This file was generated by extconf.rb
module CommandT
  module Metadata
    EXPECTED_RUBY_VERSION = '[unknown]'
    EXPECTED_RUBY_PATCHLEVEL = '[unknown]'
    UNKNOWN = true
  end # module Metadata
end # module CommandT
